% This script uses variables generated by stochasticdoublewell_main.m
% Here we generate the plots for the paper 'Bridging the Gap Between Koopmanism and Response Theory'
% Update: final figure for paper is now generated in plotting_response_averaged_diff_M.m

%% Plot invariant density & vector field
figure('Name','Density')
contourf(xdisc_mid,ydisc_mid,mu,16,'LineWidth',0.05)
daspect([1 1 1])
cc = colorbar;
cc.Label.String = '$\rho_0(x,y)$';
cc.Label.Interpreter = 'latex';
cc.Label.FontSize = 11;
xlabel('$x$','Interpreter','latex')
ylabel('$y$','Interpreter','latex')

% Add vector field
hold on
x_sparse = -1.75:0.25:1.75; y_sparse = x_sparse;
[xgrid_sparse,ygrid_sparse] = meshgrid(x_sparse,y_sparse);
quiver(xgrid_sparse,ygrid_sparse,-dVx(xgrid_sparse),-dVy(ygrid_sparse),'r','LineWidth',1)
hold off

%% Plot decay rates
% Not included in paper
figure('Name','eigenvalues (cont. time)')
notoplot = 30;
plot(real(rates(1:notoplot)), imag(rates(1:notoplot)),'bo')
xline(0)
hold off

%% Plot first 15 eigenfunctions
% Define Koopman eigenfunctions on grid
PXgrid = monodict2D([xgrid(:),ygrid(:)],Kmax);
Phigrid = PXgrid*real(Xi);
% For this system, eigenvalues should be real, and only real part will be plotted, 
% so we take real part to avoid collecting errors

% Inaccurate results in areas of low density, so we cut off edge of plot
chopoff = round(0.8/0.05);
prange = chopoff+1:length(xgrid)-chopoff;

figure('Name','Eigenfunctions')
tt = tiledlayout(3,5);

for eignum = 2:16
    Phitoplot = reshape(Phigrid(:,eignum),[length(xgrid),length(ygrid)]);
    nexttile
    contourf(xgrid(prange,prange), ygrid(prange,prange), Phitoplot(prange,prange),24,'LineWidth',0.1)
    ax=gca;
    ax.FontSize = 12;
    clim([-max(abs(Phitoplot(prange,prange)),[],"all") max(abs(Phitoplot(prange,prange)),[],"all")])
   
    % Turn on/off x,y tick labels:
    if eignum < 12
        xticklabels({})
    end
    %if mod(eignum,5) ~= 1
    %    yticklabels({})
    %end 

    title(sprintf('$\\lambda_{%d} = %0.4g$',eignum-1,rates(eignum)),'FontSize',14,'Interpreter','latex')
    pbaspect([1 1 1])
end

tt.TileSpacing = 'tight';
tt.Padding = 'tight';
xlabel(tt,'$x$','FontSize',20,'Interpreter','latex')
ylabel(tt,'$y$','FontSize',20,'Interpreter','latex')

cc = colorbar;
cc.Layout.Tile = 'east';
cc.Ticks = 0;
cc.Label.Interpreter = 'latex';
cc.Label.String = '$\varphi_j(x,y)$';
cc.Label.FontSize = 20;   

%% Plot correlation functions of odd observables

tplot_max = 180;
res = 0.1;
nplot = 0:res:tplot_max/dt;
tplot = 0:dt*res:tplot_max;

cf_filter = 100;
cf_plot_range = max_lag+1:cf_filter:2*max_lag+1;

figure('Name','Odd Correlations')

hold on
plot(lags(cf_plot_range)*dt_2,cf_x(cf_plot_range),'bo', 'MarkerFaceColor', 'b','LineWidth',1)
plot(tplot,Kcorrfn_x(nplot),'b-','LineWidth',2)

plot(lags(cf_plot_range)*dt_2,cf_4(cf_plot_range),'ro','LineWidth',1)
plot(tplot,Kcorrfn_4(nplot),'r-.','LineWidth',2)
hold off
xlim([0 tplot_max])
ylim([-0.01 inf])
box on

xlabel('$t$','Interpreter','latex')
ylabel('$C_{f}(t)$','Interpreter','latex')
legend('$f  = x$ - Numerical','$f  = x$ - Spectral','$f  = \sin(2x) + \cos(2y)$ - Numerical','$f  = \sin(2x) + \cos(2y)$ - Spectral','Interpreter','latex')

%% Plot correlation functions of even observables

tplot_max = 2;
res = 0.01;
nplot = 0:res:tplot_max/dt;
tplot = 0:dt*res:tplot_max;

cf_filter = 4;
cf_plot_range = max_lag+1:cf_filter:2*max_lag+1;

figure('Name','Even Correlations')

hold on
plot(lags(cf_plot_range)*dt_2,cf_y(cf_plot_range),'bo', 'MarkerFaceColor', 'b','LineWidth',1)
plot(tplot,Kcorrfn_y(nplot),'b-','LineWidth',2)

plot(lags(cf_plot_range)*dt_2,cf_rad(cf_plot_range),'ro','LineWidth',1.5)
plot(tplot,Kcorrfn_rad(nplot),'r--','LineWidth',2)

plot(lags(cf_plot_range)*dt_2,cf_3(cf_plot_range),'mo','LineWidth',0.5)
plot(tplot,Kcorrfn_3(nplot),'m-.','LineWidth',2)
hold off
xlim([0 tplot_max])
ylim([0 inf])
box on

xlabel('$t$','Interpreter','latex')
ylabel('$C_{f}(t)$','Interpreter','latex')
legend('$f  = y$ - Numerical','$f  = y$ - Spectral','$f  = x^2 + y^2$ - Numerical','$f  = x^2 + y^2$ - Spectral','$f  = \cos(2x) + \sin(2y)$ - Numerical','$f  = \cos(2x) + \sin(2y)$ - Spectral','Interpreter','latex')

%% Decompose into individual contributions - odd observables

linetypes_b = {'b-','b:','b--','b-.','b-','b:','b--','b-.','b-','b:','b--','b-.'};
linetypes_r = {'r-','r:','r--','r-.','r-','r:','r--','r-.','r-','r:','r--','r-.'};

figure('Name','Odd correlations: decomposition')

iter = 1;
hold on
for i=2:kn
    if abs(KoopmanCorrs_singleterm(v_x,v_x,lambda,scalarprod_matrix,i,1))>1e-3
        plot(tplot,KoopmanCorrs_singleterm(v_x,v_x,lambda,scalarprod_matrix,i,nplot),linetypes_b{iter},'LineWidth',3,'DisplayName',sprintf('$k=%d$',i-1))
        iter = iter+1;
    end
end
%iter = 1;
for i=2:kn
    if KoopmanCorrs_singleterm(vnum_4,vnum_4,lambda,scalarprod_matrix,i,1)>1e-3
        plot(tplot,KoopmanCorrs_singleterm(vnum_4,vnum_4,lambda,scalarprod_matrix,i,nplot),linetypes_r{iter},'LineWidth',2,'DisplayName',sprintf('$k=%d$',i-1))
        iter = iter+1;
    end
end

xlabel('$t$','Interpreter','latex')
ylabel('$C_{f}(t)$','Interpreter','latex')
legend('Interpreter','latex')
box on

yscale log
ylim([1e-4 1])
xlim([0 2])
hold off

%% Decompose into individual contributions - even observables

linetypes_b = {'b-','b:','b--','b-.','b-','b:','b--','b-.','b-','b:','b--','b-.'};
linetypes_r = {'r-','r:','r--','r-.','r-','r:','r--','r-.','r-','r:','r--','r-.'};
linetypes_m = {'m-','m:','m--','m-.','m-','m:','m--','m-.','m-','m:','m--','m-.','m-','m:','m--','m-.'};

figure('Name','Even correlations: decomposition')
iter = 1;

hold on
for i=2:kn
    if abs(KoopmanCorrs_singleterm(v_y,v_y,lambda,scalarprod_matrix,i,2))>1e-4
        plot(tplot,KoopmanCorrs_singleterm(v_y,v_y,lambda,scalarprod_matrix,i,nplot),linetypes_b{iter},'LineWidth',4,'DisplayName',sprintf('$k=%d$',i-1))
        iter = iter+1;
    end
end
iter = 1;
for i=2:kn
    if KoopmanCorrs_singleterm(v_rad,v_rad,lambda,scalarprod_matrix,i,1)>5e-3
        plot(tplot,KoopmanCorrs_singleterm(v_rad,v_rad,lambda,scalarprod_matrix,i,nplot),linetypes_r{iter},'LineWidth',3,'DisplayName',sprintf('$k=%d$',i-1))
        iter = iter+1;
    end
end
iter = 1;
for i=2:kn
    if KoopmanCorrs_singleterm(vnum_3,vnum_3,lambda,scalarprod_matrix,i,1)>5e-3
        plot(tplot,KoopmanCorrs_singleterm(vnum_3,vnum_3,lambda,scalarprod_matrix,i,nplot),linetypes_m{iter},'LineWidth',2,'DisplayName',sprintf('$k=%d$',i-1))
        iter = iter+1;
    end
end

xlabel('$t$','Interpreter','latex')
ylabel('$C_{f}(t)$','Interpreter','latex')
legend('Interpreter','latex')
box on

yscale log
ylim([1e-4 0.4])
xlim([0 2])
hold off

%% Following 2 sections additionally use variables generated by script response_experiments_doublewell
% Plots below not included in paper: see plotting_response_averaged_diff_M
% for final versions
%% Plot spectral & numerical Green's functions 1

tplot_max = tmax_resp;

res = 1;
nplot = 0:res:tplot_max/dt;
tplot = 0:dt*res:tplot_max;

figure('Name','Response of x to tilt')

plot(tplot,GreenFn_x(nplot),'LineWidth',2)

hold on
box on 

plot(tt_resp,gf_num_x,'rx')

hold off
xlim([0 tplot_max])

xlabel('$t$','Interpreter','latex')
ylabel('$G_{f}(t)$','Interpreter','latex')
legend('Spectral Estimate','Numerical Simulation','Interpreter','latex')

%% Plot spectral & numerical Green's functions 2

tplot_max = tmax_resp2;

res = 0.1;
nplot = 0:res:tplot_max/dt;
tplot = 0:dt*res:tplot_max;

figure('Name','Response of radius to stretch')

plot(tplot,GreenFn_rad(nplot),'LineWidth',2)

hold on
box on 

plot(tt_resp2,gf_num_rad,'rx')

hold off
xlim([0 tplot_max])

xlabel('$t$','Interpreter','latex')
ylabel('$G_{f}(t)$','Interpreter','latex')
legend('Spectral Estimate','Numerical Simulation','Interpreter','latex')

